In [1]:
import numpy as np
a=np.array((2,3,4))
a

array([2, 3, 4])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.ndim

1

In [4]:
b=np.array((5, 6, 7))
b

array([5, 6, 7])

In [5]:
x=np.zeros((2,3,4))
print(x)
print(x.dtype)
print(x.ndim)
print(x.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
float64
3
(2, 3, 4)


In [6]:
y=np.ones((3, 4, 5))
print(y)
print(y.shape)
print(y.ndim)
print(y.dtype)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(3, 4, 5)
3
float64


In [7]:
y=np.full((3,4,5),4.5)
print(y)
print(y.shape)
print(y.ndim)
print(y.dtype)


[[[4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]]

 [[4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]]

 [[4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]
  [4.5 4.5 4.5 4.5 4.5]]]
(3, 4, 5)
3
float64


In [8]:
x=np.full((2,3,4),np.pi)
print(x)
print(x.dtype)
print(x.ndim)
print(x.shape)


[[[3.14159265 3.14159265 3.14159265 3.14159265]
  [3.14159265 3.14159265 3.14159265 3.14159265]
  [3.14159265 3.14159265 3.14159265 3.14159265]]

 [[3.14159265 3.14159265 3.14159265 3.14159265]
  [3.14159265 3.14159265 3.14159265 3.14159265]
  [3.14159265 3.14159265 3.14159265 3.14159265]]]
float64
3
(2, 3, 4)


In [9]:
z=np.arange(1,20,2)
print(z)
print(z.dtype)
print(z.ndim)
print(z.shape)


[ 1  3  5  7  9 11 13 15 17 19]
int32
1
(10,)


In [10]:
%timeit np.arange(1,20,1)

2.02 µs ± 46.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
x=np.arange(10, 20, 0.5)
print(x)
print(x.dtype)
print(x.ndim)
print(x.shape)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]
float64
1
(20,)


In [12]:
x = [
        [
            1,2,3,4
        ],
        [
            1,2,2,2
        ]
]
x1 = np.array(x)
print(x1.shape)

(2, 4)


In [13]:
three_d_array = np.full((2,3,4), 0.11)
print(three_d_array)
print(three_d_array.reshape(-1, 4))

[[[0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]]

 [[0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]]]
[[0.11 0.11 0.11 0.11]
 [0.11 0.11 0.11 0.11]
 [0.11 0.11 0.11 0.11]
 [0.11 0.11 0.11 0.11]
 [0.11 0.11 0.11 0.11]
 [0.11 0.11 0.11 0.11]]


In [14]:
three_d_array.shape


(2, 3, 4)

In [15]:
z=np.linspace(1, 10, 20)
print(z)
print(z.reshape(-1, 2))
print(z.shape)
print(z.ndim)
print(z.dtype)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.47368421]
 [ 1.94736842  2.42105263]
 [ 2.89473684  3.36842105]
 [ 3.84210526  4.31578947]
 [ 4.78947368  5.26315789]
 [ 5.73684211  6.21052632]
 [ 6.68421053  7.15789474]
 [ 7.63157895  8.10526316]
 [ 8.57894737  9.05263158]
 [ 9.52631579 10.        ]]
(20,)
1
float64


In [16]:
np.linspace(0, 5/3, 6)


array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [17]:

# Make a 2x3 matrix having random floats between 0 and 1:
x = np.random.rand(2,3)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

[[0.31665545 0.0038199  0.04627124]
 [0.33750857 0.89133938 0.66186075]]
(2, 3)
2
float64


In [18]:
x = np.empty((2,3))
print(x)
print(x.dtype)
print(x.shape)
print(x.ndim)

[[0.31665545 0.0038199  0.04627124]
 [0.33750857 0.89133938 0.66186075]]
float64
(2, 3)
2


In [19]:
x[0]


array([0.31665545, 0.0038199 , 0.04627124])

In [20]:
x[1]

array([0.33750857, 0.89133938, 0.66186075])

In [21]:
x[1][0]


0.3375085704213324

In [22]:
x[0,1]


0.0038198989106157377

In [23]:
c = np.arange(1, 5)
c


array([1, 2, 3, 4])

In [24]:
c.dtype


dtype('int32')

In [25]:
c.itemsize


4

In [26]:

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
a = np.arange(24)
print(a)
b = a.reshape(2,3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
b.reshape(-1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
a=np.random.rand(2, 4)
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)


[[0.07826972 0.09459096 0.03956933 0.98882664]
 [0.30706494 0.45337699 0.85246701 0.030864  ]]
(2, 4)
float64
2


In [30]:
np.RAISE?


In [31]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[1]

5

In [32]:
a[2:5]


array([ 3, 19, 13])

In [33]:
a

array([ 1,  5,  3, 19, 13,  7,  3])

In [34]:
a[1:6:2]


array([ 5, 19,  7])

In [35]:
a

array([ 1,  5,  3, 19, 13,  7,  3])

In [36]:
a*9 + 1


array([ 10,  46,  28, 172, 118,  64,  28])

In [37]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [38]:
a[17]


17

In [39]:
a[5:7]


array([5, 6])

In [40]:
a[2:]


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23])

In [41]:
a[:3]


array([0, 1, 2])

In [42]:
print(a)
a[:10:2]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([0, 2, 4, 6, 8])

In [43]:
print(a)
a[:10:-1]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [44]:
print(a[2::2])


[ 2  4  6  8 10 12 14 16 18 20 22]


In [45]:
print(a)
print(a[2::3])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 2  5  8 11 14 17 20 23]


In [46]:
print(a[::-1])


[23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [47]:
print(a)
print(a[::-3])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[23 20 17 14 11  8  5  2]


In [48]:
b = [1, 2, 5, 7, 8]
b

[1, 2, 5, 7, 8]

In [49]:
a = np.array([1, 2, 5, 7, 8])
print(a)


[1 2 5 7 8]


In [50]:

a_slice = a[1:5] # 2, 5, 7, 8
a_slice

array([2, 5, 7, 8])

In [51]:
a_slice[1] = 1000
a_slice

array([   2, 1000,    7,    8])

In [52]:

a_slice_copy = a_slice.copy()
a_slice_copy[3] = 800
a_slice_copy

array([   2, 1000,    7,  800])

In [53]:
print(a)
print(a_slice)

[   1    2 1000    7    8]
[   2 1000    7    8]


In [54]:

another_slice = a[2:6].copy()
another_slice[1] = 23333  
print(another_slice) #Updated
print(a) #Unchanged

[ 1000 23333     8]
[   1    2 1000    7    8]


In [55]:
x = np.random.rand(3, 3, 3)
x

array([[[0.71516283, 0.63612436, 0.1621192 ],
        [0.14249278, 0.19111334, 0.08181092],
        [0.59453605, 0.80850336, 0.11269456]],

       [[0.02771622, 0.78626526, 0.21608538],
        [0.60164758, 0.01153788, 0.04143926],
        [0.06169221, 0.16950263, 0.83123475]],

       [[0.02512162, 0.91789894, 0.14983551],
        [0.371518  , 0.65073085, 0.83312772],
        [0.67647778, 0.06034834, 0.69216908]]])

In [56]:
x[0:2, 0:2, 1:3]


array([[[0.63612436, 0.1621192 ],
        [0.19111334, 0.08181092]],

       [[0.78626526, 0.21608538],
        [0.01153788, 0.04143926]]])

In [57]:
x[1:4:2, 0:2, 0:3]


array([[[0.02771622, 0.78626526, 0.21608538],
        [0.60164758, 0.01153788, 0.04143926]]])

In [58]:

A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )
print(A*B)                         # element wise product

print([[1*2, 1*0],
       [0*3, 1*4]])

[[2 0]
 [0 4]]
[[2, 0], [0, 4]]


In [59]:
print(np.dot(A, B))
print([[1*2+ 1*3, 1*0+ 1*4],
       [0*2+1*3, 0*0+1*4]])

[[5 4]
 [3 4]]
[[5, 4], [3, 4]]


In [60]:
# np.arange - Creating sequence of Numbers

a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a / b
print(c)

[20.         15.         13.33333333 12.5       ]


In [61]:
np.power(a, b)


array([     20,     900,   64000, 6250000], dtype=int32)

In [62]:

a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a // b
c

array([20, 15, 13, 12], dtype=int32)

In [63]:
#Modulus operator can be applied on NumPy arrays as shown below. They apply element wise.
a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a % b
c

array([0, 0, 1, 2], dtype=int32)

In [64]:

a = np.array( [20, 30, 40, 50] )
b = np.arange(1, 5)
c = a ** b
c

array([     20,     900,   64000, 6250000], dtype=int32)

In [65]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [66]:
m < 25


array([ True,  True, False, False])

In [67]:
m[m < 25]


array([20, -5])

In [68]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("mean =", a.mean())

mean = 6.766666666666667


In [69]:
np.prod(a)


-71610.0

In [70]:
print(-2.5* 3.1* 7*10*11*12)


-71610.0


In [71]:
import math
a = np.array([1,3,4])
m = np.mean(a)
print(m)
print(a -m)
x = (a-m)**2
print(x)
s = np.sum(x)
print(s)
v = np.var(a)
print(v)
print(v*len(a))
print(np.std(a))
print(math.sqrt(s/len(a)))

2.6666666666666665
[-1.66666667  0.33333333  1.33333333]
[2.77777778 0.11111111 1.77777778]
4.666666666666666
1.5555555555555554
4.666666666666666
1.247219128924647
1.247219128924647


In [72]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [73]:
c.sum(axis=0)  # sum across matrices


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [74]:
import numpy as np
a = np.array([[10,20],[30,40]])
b = np.array([1])
print(a+b)

[[11 21]
 [31 41]]


In [75]:

import numpy as np
import pandas as pd

In [76]:
weights = {"alice": 68, "bob": 83, "colin": 86, "darwin": 68}
weights

{'alice': 68, 'bob': 83, 'colin': 86, 'darwin': 68}

In [77]:
s3 = pd.Series(weights)
s3

alice     68
bob       83
colin     86
darwin    68
dtype: int64

In [78]:
s3 + s3


alice     136
bob       166
colin     172
darwin    136
dtype: int64

In [79]:
a = np.array([[1, 2, 3],
[4, 5, 6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
a.sum(axis=0)


array([5, 7, 9])

In [81]:
a.sum(axis=1)


array([ 6, 15])

In [82]:

b = np.array([[.1, .2, .3],
[.4, .5, .6]])

In [83]:
b

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [84]:
from numpy import linalg


In [85]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)

In [86]:
solution


array([-3.,  2.])

In [87]:
coeffs.dot(solution)


array([ 6., -9.])

In [88]:
s="my name is rahul kumar singh"
sp=s.split(" ")
new_list=[]
print(sp)
for word in sp:
    #print(word)
    word_list= list(word)
    #print("wordlist" ,word_list)
    length= len(word_list)
    word_list[0]= word_list[length-1]
    temp=word_list[length-1]
    #print(temp)
    w="".join(word_list)
    #print(w)
    new_list.append(w)
print(" ".join(new_list))
    

['my', 'name', 'is', 'rahul', 'kumar', 'singh']
yy eame ss lahul rumar hingh
